version: '3'

services:
  php:
    image: php:8.0-apache
    ports:
      - "8080:80"  # You can change the host port as needed
    volumes:
      - .:/var/www/html  # Mount your project files into the container
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test-admin-dashboard
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  # You can change the host port as needed
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8081:80"  # You can change the host port as needed
    depends_on:
      - mysql

volumes:
  mysql_data:
